@0xa156e552e5c438d3; # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("CapnProtoTest");

struct AudioData {
	senderSession    @0 :UInt32;
	frameNumber      @1 :UInt64;
	opusData         @2 :Data;
	isTerminator     @3 :Bool;
	targetOrContext  @4 :UInt32;
	positionalData   @5 :List(Float32);
	volumeAdjustment @6 :Float32;
}
