@0xa156e552e5c438d3; # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("CapnProtoTest");

struct TestMessage {
	flag       @0 :Bool;
	text       @1 :Text;
	integer    @2 :Int32;
	decimal    @3 :Float32;
	binaryData @4 :Data;
	numbers    @5 :List(UInt32);
}
